name: pipeline

on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  toolchain:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.10', '3.11']
        
    steps:
      # setup
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python }}
      - name: install dependencies
        run: pdm install

      # lint
      - name: format imports
        run: isort src tests --check
      - name: format code
        run: black src tests --check

      # test
      - name: unit test
        run: pytest tests
      - name: static typing
        run: mypy src

      # security
      - name: source code vulnerabilities
        run: bandit -r src
      - name: 3rd party vulnerabilities
        run: pdm export --prod -f requirements | safety check --stdin

      # build
      - name: build docs
        run: mkdocs build -d public
      - name: build distribution
        run: pdm build

      # keep artifacts for publish or debugging
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.python }}-artifacts
          path: |
            public/
            dist/
            pdm.lock

  deploy:
    needs: [toolchain]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      # publish pages, surprisingly complex
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: actions/download-artifact@v3
        with:
          name: 3.10-artifacts  # just one set is enough
      - uses: actions/upload-pages-artifact@v1
        with:
          path: site/
      - name: deploy github pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2

      # publish distribution to pypi
      - uses: pdm-project/setup-pdm@v3
      - name: publish package
        if: github.ref == 'refs/heads/main'
        run: pdm publish --no-build -u arne -P ${{ secrets.PYPI_PW }}
